[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "autohelm"
version = "2.0.0"
dependencies = [
  "typer",
  "protobuf",
  "nanopb"
]
requires-python = ">=3.8"
authors = [
  {name = "Sean Fish", email = "seantfish@gmail.com"},
]
description = "Automated Helm Interface"
readme = "README.md"

[project.optional-dependencies]

[project.urls]

[project.scripts]
autohelm = "autohelm.app:cli"

[tool.hatch.build.targets.wheel]
include = [
  "/autohelm/*.py",
  "/firmware",
  "/platformio.ini",
  "/proto"
]