/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_COMMAND_PB_H_INCLUDED
#define PB_COMMAND_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _Command {
    pb_callback_t efforts;
} Command;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define Command_init_default                     {{{NULL}, NULL}}
#define Command_init_zero                        {{{NULL}, NULL}}

/* Field tags (for use in manual encoding/decoding) */
#define Command_efforts_tag                      1

/* Struct field encoding specification for nanopb */
#define Command_FIELDLIST(X, a) \
X(a, CALLBACK, REPEATED, UINT32,   efforts,           1)
#define Command_CALLBACK pb_default_field_callback
#define Command_DEFAULT NULL

extern const pb_msgdesc_t Command_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define Command_fields &Command_msg

/* Maximum encoded size of messages (where known) */
/* Command_size depends on runtime parameters */

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
