name: PlatformIO CI

on: [workflow_dispatch]

jobs:
  micro_ros_platformio:
      runs-on: ubuntu-22.04
      container: ubuntu:22.04

      strategy:
        fail-fast: false
        matrix:
          platform: [teensy41, pico]

      steps:
      - uses: actions/checkout@v3
        with:
          path: repo
      - name: Install environment
        uses: ./repo/.github/actions/platformio-env
      - name: Build
        shell: bash
        run: |
          export PATH=$PATH:~/.platformio/penv/bin
          cd repo
          pio run -e ${{ matrix.platform }}
